### ISSUE TITLE
[Plugin Bug] Icons overlap when scaling up Dalamud UI

### ISSUE THREAD

**Issue by jcql** [Hildaware/Hilda#1]
**Describe the bug**
If your Dalamud UI scale is higher than 1.0 the priority set icons overlap more the higher the scale. Some of the indicator icon positions also become incorrect.

**To Reproduce**

1. Open Dalamud Settings
2. Go to Look + Feel
3. Increase Font Scale
4. Observe Hilda icons

**Screenshots**
![image](https://user-images.githubusercontent.com/16084506/166122921-2b959b81-7a83-417c-b493-82f97076c5c4.png)

![image](https://user-images.githubusercontent.com/16084506/166122911-0359bb87-b966-4d54-88dc-c0e56caec139.png)

Reported by [SurprisedElezen](https://discord.com/channels/945412133104021544/945421206201446501/969863835047559199)

**Comment by bferrari352** [comment]
Fixed in [v0.0.13.0](https://github.com/Hildaware/Hilda/releases/tag/0.0.13.0)
